cache:
  paths:
    - /root/.cache
    - /root/.m2

pages:
  image: debian:10.8
  stage: build
  only:
    - master
  script:
    - apt-get update && apt-get install -y maven openjdk-11-jdk
    - mvn install
    - mkdir public
    - cp webviewsyntaxexamples/target/webviewsyntaxexamples-0.0.0/webviewsyntaxexamples/webviewsyntaxexamples.js public/entry.js
    - cp webviewsyntaxexamples/src/main/java/main_dev.html public/index.html
  artifacts:
    paths:
      - public